name: CI/CD pipeline for Java with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: gradle build

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run tests
        run: gradle test

  deploy:
    runs-on: ubuntu-latest

    needs: test

    environment:
      name: production

    steps:
      - uses: actions/checkout@v3

      - name: Build with Gradle
        run: gradle build

      - name: Build Docker image
        run: docker build -t elearning-demo .

      - name: Push Docker image to Docker Hub
        run: |
          docker login ghcr.io
          docker push ghcr.io/your-username/elearning-demo
          docker tag ghcr.io/your-username/elearning-demo:latest
          docker push ghcr.io/your-username/elearning-demo:latest

      - name: Deploy to DigitalOcean
        uses: actions/deploy-to-digitalocean@v1
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
          app-name: eLearningPlatform
          region: nyc3
          image: ghcr.io/your-username/elearning-demo:latest
